### ISSUE TITLE
BernsteinPolynomialTest fails with clang 12.0.5

### ISSUE THREAD

**Issue by deltaLuki** [tataratat/bezman#14]
In branch #13  the test case `BernsteinPolynomialTest` - `TestEnvelopAndPartitionOfUnity` fails when I run the test on my mac (Apple clang version 12.0.5). Is this version no longer supported (CI runs with clang 14.0.0 - pass the test)? Then we have to update the README.

**Comment by jzwar** [comment]
Please check if this is still relevant after the clean up and report
