### ISSUE TITLE
Improve CMAKE 

### ISSUE THREAD

**Issue by jzwar** [tataratat/bezman#2]
@j042 suggested the following improvements to bezman in his last PR #14 

- Personally, I think you shouldn't start `#include` path from the root. This leads to including parent directory of your `bezman` root, which can cause unwanted behavior. I'd use something like `<bezman-root>/include/bezman`, so that you can include `<bezman-root>/include`, but you can still have your `#include` start with bezman. Nice, informative, and charming.
- Rename `ENABLE_LOGGING` to, for example, `BEZMAN_ENABLE_LOGGING` - this way you avoid possible conflict with other packages
- Rename cmake option `GOOGLETEST` with `BEZMAN_BUILD_TEST` or `BEZMAN_GOOGLETEST` - same reason as above
- Have you thought about adding option to download `googletest` only if there's no googletest / installed version is incompatible? Could be nice.

**Comment by j042** [comment]
I think the third one is covered in #1 (BEZMAN_GOOGLETEST). I can create a PR for other points, if you'd like.
